import java.util.ArrayList;
import java.util.Collections;
import java.util.Arrays;
import java.util.Random;
public class Deck {
  private Card[] deck = new Card[]{
    new Card("The Fool", "Let go of expectations and trust your instincts.", "Let yourself be spontaneous enough to stretch beyond the realm of logic. There is no advantage to be gained by thinking you possess the knowledge, power, or control to direct reality.\n Open and receive without question, instead of trying to manage what's happening right now. The Fool has no ambition to manipulate a specific outcome.\n Just be happy to be part of the whole.", ""),
    new Card("The Emperor", "You have the wisdom and authority to achieve your goals.", "You have the necessary abilities to be the final authority.\n This situation is an opportunity to showcase your competence and skill. Act with the confidence of someone who knows how to take care of business.", ""),
    new Card("Strength", "Balance your primal force with intution and compassion.", "Demand and expect the same from others who have some power in this situation.\n You cannot challenge them to live to a higher standard if you, yourself, have not yet done so. Influence others by setting an example of integrity.\n Your self-esteem will increase to the degree that you succeed in your efforts.", ""),
    new Card("The Hanged Man", "You have reached a crossroads, making it possible to clear the slate and start over.", "Stop resisting your circumstances and let some time go by. Eventually, you will be released a little wiser and not much the worse for wear.\n You will come to realize in time how you collaborated with the problem. However, the issues you were stuck on when you were first hung up have subsided and no longer concern you.\n You are free to take up new endeavors. You will ultimately feel refreshed and grateful that you were derailed from your former track.", ""),
    new Card("The Tower", "Because of circumstances beyond your control, you have no choice.", "Now you may be at the forefront, acknowledging and accepting the bracing presence of the future bursting in on the present.\n Try to mediate the harsher parts of the changes as they unfold, so the most vulnerable are the most cushioned. Acknowledge yourself, as well as the others in your life, who are offering their resources to usher in a better future.", ""),
    new Card("Judgement", "You have the power to make changes and feel complete.", "It's not necessary to reject others, but refuse to be manipulated by those who cry foul.\n This process isn't about them anyway. It is about you and the desire you feel to change your life and become a more complete person.\n Trust your impulses and allow this remarkable awakening to happen.", ""),
    new Card("The Magician", "Be creative and stay open -- your possibilities are endless.", "You do not have to understand it all intellectually. Besides, intuition is your ace in the hole. Respond in a spontaneous manner to what is right in front of you. There is no reason to hold yourself back.\n Your natural urges are exactly what is needed, and, your ingenuous timing and elegant style will help smooth over any awkwardness.", ""),
    new Card("The Hierophant", "Expand your inner knowledge and share it with others.", "Earn respect and recognition by completing your education and broadening your experience.\n If you already have all the necessary experience you need, then rewrite your resume so others can appreciate who you are and what you can bring to a situation. Focus on your goal and be determined.\n You may be destined to be a master in your realm.", ""),
    new Card("The Hermit", "Gaze into the mysteries of your inner life.", "Now may be the moment for you to tell everyone to leave you alone. When you are fully ready, you will be able and willing to give others what they need.", ""),
    new Card("Death", "Shed the old to make room for the new.", "Do not allow nostalgia and outworn loyalties to hold you back. Be willing to go through whatever it takes to get to where you really want to be.", ""),
    new Card("The Star", "Rise above your day-to-day and connect with the divine.", "Now is a period for quiet contemplation. Listen for the voice within.\n Anything that would interfere with this communion may not be serving your best interests right now.", ""),
    new Card("The World", "You are in a timeless state of grace where all is well.", "What matters is divine intention. Whether or not human beings approve is less important.\n If you allow your ego to inflate, however, you cease to be useful to the greater plan.", ""),
    new Card("The High Priestess", "Get your self out of the way and become attuned to a more spiritual view.", "Until you consider this as vital to your well-being as the need to eat and sleep, you are likely to be eternally restless and deeply dissatisfied.\n A spiritual routine that suits your temperament, practiced every day, is the most trustworthy path to freedom.", ""),
    new Card("The Lovers", "Integrate two potential realities or let go of one of them.", "Be willing to make some compromises, then stick with the commitments you finally make. Trust your intuition along with your rational intellect, and once you make your choice, carry it out with conviction.", ""),
    new Card("Wheel of Fortune", "Learn to go with the flow without resisting ups and downs.", "This is a safe place for you to be. You are watched over and protected as you go round and round the wheel.\n You will learn a lot. You will also learn it quickly, and what you absorb will benefit you for a long time to come.", ""),
    new Card("Temperance", "The time is now for self-healing.", "Prepare to use spiritual practices, studies, or lifestyle changes that can assist you in your quest.\n A tremendous amount of benefit is available if you can organize yourself and be disciplined at this time.", ""),
    new Card("The Moon", "This is an opportunity to draw messages from your inner self.", "The everyday mind may not be prepared for strange oceanic circumstances.\n Plus, it has no game plan. Your intuitive body will support you unerringly if you do not interfere with or try to control what you perceive.\n A better approach would be to meditate. Try to just be a witness. Do nothing; let nature carry you forward. This may be your best option in this situation.", ""),
    new Card("The Empress", "Look for opportunities to be generous, warm, and nurturing.", "Demonstrate this through caring actions, a forgiving and generous attitude, and wise understanding of others' needs and struggles.\n Bring a healing influence to the current situation and take full credit for the supportive part you play.", ""),
    new Card("The Chariot", "Use your powers of freedom and flexibility to drive your future.", "You may be asked to live out of a suitcase and consider every place your home for a while.\n Be receptive to new people who come into your life. Most especially, become more fluid and taste the joys of freedom.\n The Charioteer is nothing if not self-sufficient. Be prepared and self-contained for the changes that will sweep in and carry you with them.", ""),
    new Card("Justice", "Balance the scales to support truth and serve the greatest good.", "As you witness people's account of themselves, your understanding will go beyond the words you hear.\n Subtle inferences and clues will reveal the truths that will enable you to make a wise and accurate assessment.", ""),
    new Card("Devil", "Put subtlety aside and empower your passion and confidence.", "Assert your agenda, express yourself honestly, and let the chips fall where they may.\n Your best bet could be to express your true emotions, possibly even including anger. Acknowledge that you have whatever feelings you have.\n While it may not be necessary to act out what you feel in every situation, accepting the power and depth of your inner experience enables you to remain true to yourself.", ""),
    new Card("The Sun", "You are in the right place at the right time.", " Step into the full light of truth and reveal your motives and principles. Once done, you will no longer give away power to the people that criticize and shame you. Focus on the positive and the real.\n Your authentic shining self can be a light for others if you project it without contrivance.", ""),
    new Card("Ace of Wands", "Stay attentive to your goal even as change accelerates.", "You may need to make your move soon, so make sure you are fully prepared. Trust your instincts and spontaneity. When the opportunity comes you may want to seize it without hesitation.\n So quicken your senses and raise you", ""),
    new Card("Two of Wands", "Assess your situation with patience and self-restraint.", "Keep meditating, watching the situation and witnessing the forces at work.\n At some point you will have enough information to see clearly.\n The decision-making process will be over and the choice will be clear.", ""),
    new Card("Three of Wands", "You are prepared to take risks to explore new opportunities or enterprises.", "Every fiber of your being may be saying this is a great opportunity, even if those around you aren't as convinced.\n There's nothing to lose from taking a risk; this is a great moment in your entrepreneurial growth.\n Make your move and sort out the details later.", ""),
    new Card("Four of Wands", "When you act upon a shared vision it will have far reaching effects.", "Your enthusiasm empowers your vision, which is thriving with possibilities.\n As you share more freely what is on your mind and in your heart, others will see themselves in your vision, so you naturally receive approval, support, assistance and abundance.\n In your own way, you are addressing a universal need.", ""),
    new Card("Five of Wands", "Let your focus be on advancing your cause.", "Identify what energizes you, what you would fight for and what you are passionate about -- even when you're tired or discouraged. Strive to make that the centerpiece of your mission. This is how you find your livelihood and establish your path of service.", ""),
    new Card("Six of Wands", "Your enthusiastic stewardship is producing dramatic results.", "You may find yourself becoming something of a leader.\n Usually the first person to break away from conventional thought is the one to define a new trend.\n Under the circumstances, there is a solid need for a fresh voice and vision -- so make your move. Those around you who are ready for change will support your leadership.", ""),
    new Card("Seven of Wands", "A positive attitude and strong potential will prime you to achieve your personal best.", "Even if slightly unprepared, you may want to push yourself beyond your usual limits, thinking in larger terms and tweaking your competitive nature.\n Time and effort spent in preparation could pay off handsomely. You might be the one who vaults right over the heads of those who thought they could outdo you. Move beyond rhetoric and verbal challenges.\n Now could be the moment to prove what puts you head and shoulders above the rest by demonstrating it in action.", ""),
    new Card("Eight of Wands", "Accelerating growth challenges you to keep up with what you are creating in your life.", "Even if you had to leave it all behind, you know you could start all over among total strangers and succeed once again.\n This valuable self-confidence makes you free to strike out in new directions and not just cling to past successes and previous accomplishments.", ""),
    new Card("Nine of Wands", "Find someone who can fill in for you and take time to refresh your energy.", "There is nothing more to bring to the mission unless you regenerate and restore the energy you have put into the cause.\n While it is praiseworthy to give all you have for something or someone that means a lot to you, masochism and martyrdom are ill advised.\n Take a break. No one can fault you for it now.", ""),
    new Card("Ten of Wands", "You are beginning to realize that what you have been pursuing is actually internal.", " Now may be the time to reach deep into yourself and identify your purest, most wholesome impulses.\n As you do this, allow your optimistic and honorable side to see what's good about the world.\n Look beyond the challenges, setbacks, disappointments and frustrations you tend to see so easily.\nAs you reawaken your high minded inner child, you will refresh your daily life with a joyful purpose.", ""),
    new Card("Page of Wands", "You are an agent of innovation and change.", "Think of yourself as a secret agent for the greater good. In due time, others may recognize the role you play in the transformation from divisiveness to unity. However, right now you are being asked to watch quietly from the sidelines.", ""),
    new Card("Knight of Wands", "A new journey of discovery is about to be embarked upon.", "Not only can you get a clear sense of the proper path, but you will also have enough instructions to be self-directing. Necessary skills and resources are available to you, and the time is right for you to act.\n Once you get started, you may be surprised how easy it can feel, but don't be seduced by that feeling.\n There will be comfortable stretches of the road and there will be distinctly uncomfortable ones. Know that any form of motion is better than no motion.", ""),
    new Card("Queen of Wands", "Decisiveness and a willingness to lead produce tangible rewards.", "A perceived deficiency in leadership may make you want to take hold of the reins, but don't do it! Restrain yourself and remain loyal to your higher-ups.\n Stay focused and energetic.\n Enthusiastically confront the challenges directly in front of you. Perform in good faith and encourage others to do the same.", ""),
    new Card("King of Wands", "Stay balanced and use power wisely to set a good example.", "You are the determining factor in this situation and circumstances will proceed in the direction that you steer them.\n Indecision or doubt are not appropriate responses when clarity and confidence are critical.\n As you take on a bigger role, it will begin to feel more comfortable.\n Seize the opportunity to influence events, because everything is waiting for you.", ""),
    new Card("Ace of Cups", "A fountain of abundance nourishes your life.", "Look with the eye of a loving parent or companion upon the people and things you come into contact with.\nMake a conscious decision to approve of and delight in even the quirky developments that make the world turn.\n No one can be perfect at such unconditional acceptance. Still the practice will sweeten your day to day life.\n Your magnetism will increase and more loving people may enter your life.\n The whole world will benefit as this becomes second nature to you.", ""),
    new Card("Two of Cups", "Your emotional, psychic and spiritual lives are quickening like spring.", "You have nothing to lose and everything to gain. Life is a relationship game.\n It's a great privilege to share with others who are so complementary and compatible.", ""),
    new Card("Three of Cups", "Celebrate friendships and close companions.", "Think of this occasion as a celebration, where their support helps you find success in your work.\n There may be something here for everyone to contribute. Put yourself in the loving hands of your family connections and your trust will be well rewarded.\n The synergy between you could enhance each individual's talent and creativity.\n You will love the results!", ""),
    new Card("Four of Cups", "Your will has dissipated and your mind is distracted from its true goal.", "Decide that you are not as heavy as the cup of earth, not placid as is the cup of water, not turbulent as is the cup of air.\n Rather, now may be the time to be as aroused as is the cup of fire.\n This arousal may constitute liberation from the circumstances that may have brought you here.", ""),
    new Card("Five of Cups", "Take action to change past patterns.", "If something is truly yours, it cannot be lost.\n When you are experiencing feelings of loss, it may be because of an inappropriate emotional attachment.\n If you promise things that you cannot deliver, then you might be setting yourself up for disappointment to follow.\n In overestimating our abilities, we are forced to face our limits.\n Be grateful that as the cups fell, you lost only three of the five.\n Two are still intact, pristine and full of sacred energy.\n Do not cling to the setback. Focus on the potential.", ""),
    new Card("Six of Cups", "You need to be more powerful, directing the flow rather than following.", "Until you analyze the past, you will continue to drift with its current.\n Distill everything that is worthwhile from your memories and get as much value from it as you can.\n Then use this as motivation for change. Make the very best use of hindsight, employing new strategies and trying new angles on these recurring issues.", ""),
    new Card("Seven of Cups", "Among your many options, choose the one closest to your heart.", "Allow yourself to imagine a truly positive outcome for this situation.\n Perform an exercise in creative visualization by relaxing your guard and letting go of your fears. As the dreamscape unfolds, your electro-magnetic chemistry is stimulated to a point of achieving greater confidence in yourself and in what you are doing.\n Even if it's only a temporary break from your fears, this is a helpful exercise because it gives your psyche and body a dose of unlimited thinking and optimism.\n Think positively -- the results could truly be amazing.", ""),
    new Card("Eight of Cups", "You are strong enough to gain wisdom from a challenging experience.", "Do not deny this pessimistic tendency.\n Failing to recognize the truth only causes repression that flares up in another part of our psyche. Instead, seek to understand and accept the hesitation and the fear you may feel, and come to terms with them. Then you can put some old emotions in their rightful place--out of the way.", ""),
    new Card("Nine of Cups", "You are finally where you had hoped and dreamed to be.", "Allow yourself to be attracted to what feels supportive.\n Avoid what feels harsh, critical and judgmental.\n If this requires that you change your style, so be it. The results of being intuitive are generally far superior to the results of being emotionally guarded and overly rational.", ""),
    new Card("Ten of Cups", "Inner and outer harmony is cause for celebration.", "It's essential to follow a teamwork approach in order to maximize the benefits for yourself.\n The good will that will emerge from such an approach will last long after the project is over.\n You will be generously rewarded later if you take a selfless approach at this time.", ""),
    new Card("Page of Cups", "Beware forgetting to look out for yourself lest you be played for a fool.", "Make sure you understand what is needed and serve the situation with loyalty.\n Look at individuals around you as the embodiment of the Divine, and try to fulfill each one's needs.\n Be unconcerned with the outcome.\n Later you will understand why you needed to be in this position.", ""),
    new Card("Knight of Cups", "The final steps of a long journey are about to be completed.", "Be humble enough to look at things through new eyes.\n At a deep level, your heart and soul are being nourished.\n Don't be tempted to run away again -- this is where you belong. Your entire journey was designed to bring you home with new appreciation.", ""),
    new Card("Queen of Cups", "You are called upon to be a loving master of emotional integrity.", "You do not want your loved ones or teammates to become complacent or dependent, as if they can take your support for granted with little or no consideration for your needs.\n Cultivate an awareness of love as freely giving and receiving.\n In the process, help clarify the important difference between receiving energy and taking it. Do not allow your willingness to give be misunderstood or abused, as if it were a weakness.", ""),
    new Card("King of Cups", "This is your time to shine and for your accomplishments to be recognized.", "As this sweetens the environment, others will be inspired to raise their own motives and intentions to match yours.\n You will be providing an important kind of leadership that uses strong reassurance to help everyone work together.\n The most persuasive thing about you is the example of generous behavior that you exhibit -- much more powerful than preaching alone.", ""),
    new Card("Ace of Swords", "You are clear about the principal objective you need to accomplish.", "Just concentrate on making your impact.\n This could be your moment. The arrow is pointed straight at the target.\n Your eye is keen, your grip is firm.\n Let that arrow fly! If you set aside distractions and hit your mark, you will be rewarded with insight and clarity.\n Remember that this is not the time to hold back, worrying about the consequences.\n When you access this level of truth, you are very likely to cut through all illusion and nonsense.", ""),
    new Card("Two of Swords", "Spend some time gathering information before taking action.", "Neither allow others to push you beyond your boundaries, nor permit yourself to act impulsively.\n You need to fully assimilate the situation before making any moves even if not having a solution as soon as you want causes tension.\n Have patience.\n There are circumstances in which action is better than non-action. This, however, is not one of them. Remain silent as much as possible and allow things to settle. A little meditation can help you achieve greater objectivity.\n You do not have enough information, as all the evidence hasn't come in yet.", ""),
    new Card("Three of Swords", "Misunderstandings are straining a relationship to the breaking point.", "Separate yourself from people and forces you do not feel compatible with.\n Grow a thicker skin. Use your creativity and imagination and seek out situations where the way you see things makes sense to those around you.\n Move towards those who can embrace and appreciate your talents and all you have to contribute.", ""),
    new Card("Four of Swords", "Summon creativity and resourcefulness from the depths of your being.", "It might be that your ideas are not ripe enough or that you are not ready to listen to feedback from others.\n If you spend more time in contemplation, you may successfully disregard the emotional occupations and biases of others.\n For now, closely observe inner events. The time for sharing will come later.", ""),
    new Card("Five of Swords", "A feeling of imbalance and negativity prevails.", "Try not to be too quick to anger or jump to conclusions.\n Just because others may have a pessimistic sense of the world, their reality does not have to undermine yours.\n There is certainly no point in struggling or competing with them.\n Your challenge now is to learn how to sidestep confrontation and evoke a more evolved response from people. At the very least, be assertive about setting boundaries for yourself.", ""),
    new Card("Six of Swords", "Use a combination of technical skill and intuition to reach your goals.", "If the game plan has become clear, your next step could be to commit yourself to pursue changes that will lead to improvement.\n Overcome the tendency to get distracted. You do not have time for approval seeking. Once you initiate action, others will be grateful for your clear thinking and quick reflexes.\n It's a special gift to be able to navigate in times of rapidly changing and unpredictable circumstances, when a cool head and right timing are most essential.", ""),
    new Card("Seven of Swords", "You have trained yourself to instinctively notice the opportunity.", "You may have enough of an overview to see how to advance through the maze and achieve your goal.\n Continue to envision unobstructed success. Even as the path you are walking changes and the circumstances around you obscure your view, keep the desired outcome clear and sharp in your mind. You will quite likely reach your goal and gain tremendous self esteem in the process.", ""),
    new Card("Eight of Swords", "This is your moment to be tested and tried.", "Be willing to make the rigorous effort that is being called for now.\n Perform wholeheartedly, with good faith and hopefulness. As such, you'll forestall bickering and criticism, prevail against negative forces and overcome the demons of doubt and resistance.\n Get excited about your challenges; be confident that you have what it takes to improve the situation.\n If you do your internal homework, the external situation will open up for you.", ""),
    new Card("Nine of Swords", "Allow yourself to look forward to the future with optimism.", "This could be a time to cut your losses.\n If so, recognize how much time and energy you have sacrificed to a way of being that's not right for you. If you can do this you will look back at this time in your life as a turning point.\n This may be an opportunity to heal as you shed a heavy burden that weighs you down.", ""),
    new Card("Ten of Swords", "You are up against the wall, and it is appropriate to admit it.", "The situation can be compared to a hurricane moving through the neighborhood.\n You can't be sure whether it is going to pass over a corner of the field or whether it is going to slam into your house.\n In the face of such unpredictability, protect yourself, hope for the best and wait it out. Sometimes, an extreme turn of events serves as a pressure relief valve for all the unexpressed and unresolved energy that had been building up.\n Trust the process even though things may seem pretty drastic right now.", ""),
    new Card("Page of Swords", "Clarify your motives before you get involved.", "In contrast to times when one can best serve the greater good by being visible and heroic, this is a time when you must keep your own counsel, cover your tracks and stealthily accomplish what would be impossible to complete without privacy. Reduce your profile and increase your anonymity, no matter how your self-image might suffer.\n Although it would be gratifying to accomplish what needs to be done and be aboveboard about it, that cannot be a priority at present.", ""),
    new Card("Queen of Swords", "This is a good time to assert your individuality.", "There are times in life when no one can take care of you as well as you can. Leave sentimentality behind and take action. Make important decisions for yourself because it's up to you.\n You are the final judge.", ""),
    new Card("Knight of Swords", "When you answer a challenge, prepare for the consequences.", " Emulate his ability to communicate successfully by keeping your conversations impersonal and humorous so no hurt feelings are provoked.\n Practice your negotiation skills so you will be in shape for imminent diplomatic challenges as they arise. A sparring partner could help you learn to control impulsive comments and stem your urge to be right at the expense of others being wrong.", ""),
    new Card("King of Swords", "Employ patient listening and ask penetrating questions.", "Instead, draw your own conclusions. Spend time reviewing all the ramifications because this King of Swords requires a thorough, methodical examination of ideas and possibilities. Call forth the sober and wise part of yourself -- the elder father figure.\n Then act on the instructions given you.", ""),
    new Card("ACE of Coins", "You are becoming increasingly aware of your contribution and value.", "This card advises that if you work a little bit every day toward your long-term goal,\n at some time in the future you will discover that you have accumulated magnificent results.\n The secret of achieving success does not lie in inflating your dreams to grandiose levels; instead it comes about by choosing your direction wisely,\n while humbly and faithfully taking one step at a time.", ""),
    new Card("Two of Coins", "Wait patiently for circumstances to sort themselves out.", "Ask yourself -- are all the facts in yet? Or is the coin still flipping in the air?\n There is no need to be goaded into premature decisions or actions.\n Act only when you are able to do so with a unified heart and mind.", ""),
    new Card("Three of Coins", "Your leadership in a cooperative effort brings exceptional results.", "Expect new and exciting offers. When they arrive, accept them graciously.\n Why hide your light under a bushel?\n It does not become you to display false modesty.\n Practice saying to yourself, Thank you, I accept the compliment until you learn to fully let in this kind of affirmative grace with ease.", ""),
    new Card("Four of Coins", "Cultivate a feeling of gratitude and make the best use of your advantage.", "However, if you are frivolous or foolish, your behavior could undermine both your inheritance and the well being of others who are connected to it. In many decks, we see the image of a person who is stuck in his or her misunderstanding of how the material plane works.\n He's afraid to let go of his four measly coins, because he doesn't know he has to give in order to get. When looked at this way, this is the card of poverty consciousness", ""),
    new Card("Five of Coins", "Consider carefully what consequences may result from joining forces.", "Put your heads together and devise a bold plan for future objectives and decide how to invest in their success.\n This Five of Coins recommends teamwork and the mutual benefits a combined effort can yield.", ""),
    new Card("Six of Coins", "You are in a position to be generous if you want to be.", "You have to constantly check your intentions so that you are not expecting something in return.\n Do not for a minute feel proud about doing someone a favor.\n In truth what you are doing is paying back an old debt to those who served as your mentors.", ""),
    new Card("Seven of Coins", "Your personal power is growing and others are taking notice.", "The path to success is paved by perseverance.\n Glamorous or flashy moves cannot take the place of consistent steps in the right direction.\n If you do not understand this, perhaps you are moving in the wrong direction or are not motivated strongly enough.", ""),
    new Card("Eight of Coins", "Give yourself credit for the quality work you are producing.", "This is an important time for meeting goals.\n However, do not work so hard that quality suffers.\n You are in a position where your effort can make a big difference.\n Apply yourself. Do the work and you will be rewarded with flexibility and freedom.", ""),
    new Card("Nine of Coins", "The abundance you enjoy allows you the freedom to be yourself.", "Hard work has brought you to a place where you could earn and receive grace, comfort, and freedom -- whether that be personal, emotional or financial.\n Exercise your imagination and create an abundant, sustainable, and enjoyable lifestyle (or relationship) for yourself.\n Acknowledge the friends and others who were loyal to you during the difficult times.\n Gather your dreams and get ready.\n You deserve this happiness.", ""),
    new Card("Ten of Coins", "You are required to meet obligations.", "Think of every act of spending and investing and securing as the sowing of seed that will sprout and produce another money tree in somebody else's yard.\n How can you get really clever and inventive at throwing those seeds? This is your next assignment.", ""),
    new Card("Page of Coins", "You are reinventing yourself to create a better fit with your chosen profession.", "Leave no stone unturned.\n See if you can figure out why their experiments went the way they did and what you might do differently that could change the outcome.\n Passionately hunt for the missing pieces overlooked by those who came before you. Remember that the mind of a beginner is an open channel for genius.\n Let that openness lead you and you will instinctively penetrate to the heart of the matter", ""),
    new Card("Knight of Coins", "Cultivate your investments using good timing and skillful management.", "The entire endeavor will be enhanced significantly by the resources you bring to it and you will be blessed tenfold.\n Expect to supervise and guide the project as well as influence the outcome of events.\n Without you on board, this endeavor is just another good idea.", ""),
    new Card("Queen of Coins", "Use your your penetrating intuition to divine new meanings.", "Proceed with confidence and do what you so strongly feel must be done.\n Since the Queen of Coins is often the person with the best intuition in the crowd, you may feel at first as if you are going against the grain, only to later find yourself becoming the leader of a new trend.", ""),
    new Card("King of Coins", "Make unpressured choices, dream big dreams -- and be generous.", "Make your moves with authority and trust in your actions without waiting for acknowledgment or approval.\n Soon enough you will receive blessing after blessing.\n If you can learn to feel that kind of confidence in your body and get comfortable with it as your natural state, you will attract the support you desire.", "")
  };
  private ArrayList<Card> current_deck;
  private Random rng;
  Deck(int seed) {
    current_deck = new ArrayList<Card>(Arrays.asList(deck));
    rng = new Random(seed);
    Collections.shuffle(current_deck, rng);
  }
  public Card draw() {
    Card card = current_deck.remove(0);
    card.setReverse(rng.nextDouble()>0.5);
    return card;
    // return deck[(int)(Math.random()*deck.length)];
  }
}

class Card{
  //Main Arcaina
  String name;
  String description;
  String anti;
  boolean reverse;
  String intro;
  Card(String name, String intro, String description, String anti) {
    this.name = name;
    this.intro = intro;
    this.description = description;
    this.anti = anti;
  }
  public void setReverse(boolean reverse) {
    this.reverse = reverse;
  }
  public void write() {
    Writer.cyan(name);
    Writer.blue(intro);

    if(reverse){
      Writer.say(anti);
    } else{
      Writer.say(description);
    }

  }
  public String toString() { return name+"\n"+intro+"\n"+description; }
}
